### ISSUE TITLE
Handling not root level common folder

### ISSUE THREAD

**Issue by ddonukis** [cognitedata/function-action-oidc#39]
### Problem
When providing a path (e.g. `src/common`) instead of a folder name to the `common_folder` input the action fails to include the common code into the zip file.

### Slack thread
https://cognitedata.slack.com/archives/C010VCGKBCM/p1669210271655089

**Comment by Magssch** [comment]
Bumping this thread, it would be great to be able to deploy a nested common folder when working with monorepos. Considering a nested structure is currently supported for the functions themselves, I think it would be better if this works the same for the common folder as well. I currently can't find a way to work around this because of this restriction (see e.g. https://github.com/cognitedata/function-action-oidc/pull/73). Would this be solved by supporting a config for setting the working directory within the github action?

**Comment by Magssch** [comment]
Nvm, I see now that this is being worked on in https://github.com/cognitedata/function-action-oidc/pull/75

**Comment by haakonvt** [comment]
@ddonukis @Magssch  This is now available by using `v2` thanks to @petreeb !
```
- name: Deploy and schedule ${{ matrix.function }}
  uses: cognitedata/function-action-oidc@v2
```

I would treat this as beta for now, please provide feedback if anything is not working as expected!
